<!DOCTYPE html>
<html>
<head>
    <title>Register</title>
</head>
<body>

<h2>Register</h2>

<form action="/register" method="post">

    <label>Username:</label>
    <input type="text" name="username" required>

    <br>

    <label>Password:</label>
    <input type="password" name="password" required>

    <br><br>

    <button type="submit">Register</button>

</form>

<a href="/login">Login</a>

</body>
</html>